<?php
ini_set('MAX_EXECUTION_TIME', '-1');
ini_set('memory_limit','2048M');
if ( ! defined('BASEPATH')) exit('No direct script access allowed');
 
class Admin_Chart extends CI_Controller {
 	public function __construct() {
 	    
		parent::__construct();
		$this->load->helper('form');
		$this->load->helper('url');
		$this->load->helper('html');
		$this->load->model('profile_model');
		$this->load->model('admin_model');
		$this->load->model('home_model');
		$this->load->library('form_validation');
		$this->load->library('email');
		//$this->load->model('session_checker_model');
		//if(!$this->session_checker_model->chk_session())
		//	redirect('admin');
		date_default_timezone_set("America/Chicago");
		// ini_set('display_errors', 1);
	 //    error_reporting(E_ALL);
	}

	public function trends_original() {
		$today2 = date("Y");
		$last_year = date("Y",strtotime("-1 year"));
		
		$cday = date("Y-m-d",strtotime("-1 days"));
		$lday = date("Y-m-d",strtotime("-8 days")); 
		$monday = strtotime("last monday");
		$monday = date('w', $monday)==date('w') ? $monday+7*86400 : $monday;
		$sunday = strtotime(date("Y-m-d",$monday)." +6 days");
		$sunday1 = strtotime(date("Y-m-d",$monday)." -7 days");
		$sunday2 = strtotime(date("Y-m-d",$sunday1)." +6 days");
		$this_week_ed1 = date("Y-m-d",$sunday2);
		$this_week_sd1 = date("Y-m-d",$sunday1);
		$this_week_sd = date("Y-m-d",$monday);
		$this_week_ed = date("Y-m-d",$sunday);
		$last_date = date("Y-m-d",strtotime("-8 days"));
		$date = date("Y-m-d",strtotime("-1 days"));

		$getDashboard = $this->db->query("INSERT INTO sales_trend_admin values ('', 
			(SELECT sum(amount) as Monday from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '1' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '1' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as Tuesday from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '2' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '2' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Wednesday from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '3' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '3' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Thursday from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '4' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '4' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Friday from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '5' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '5' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Satuday from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '6' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '6' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Sunday from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '7' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '7' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Monday_l from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '1' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '1' and status='confirm' )x group by day1 )  ,
			(SELECT sum(amount) as Tuesday_l from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '2' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '2' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as Wednesday_l from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '3' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '3' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as Thursday_l from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '4' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '4' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as Friday_l from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '5' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '5' and status='confirm' )x group by day1 )  ,
			(SELECT sum(amount) as Satuday_l from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '6' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '6' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Sunday_l from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '7' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '7' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Monday from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '1' and status='confirm'   union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '1' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Tuesday from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '2' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '2' and status='confirm' )x group by day1 )    ,
			(SELECT sum(fee) as Wednesday from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '3' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '3' and status='confirm' )x group by day1 )    ,
			(SELECT sum(fee) as Thursday from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '4' and status='confirm'   union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '4' and status='confirm' )x group by day1 )    ,
			(SELECT sum(fee) as Friday from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '5' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '5' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Satuday from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '6' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '6' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Sunday from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '7' and status='confirm'   union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '7' and status='confirm' )x group by day1 )    ,
			(SELECT sum(fee) as Monday_l from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '1' and status='confirm'   union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '1' and status='confirm' )x group by day1 )    ,
			(SELECT sum(fee) as Tuesday_l from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '2' and status='confirm'   union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '2' and status='confirm' )x group by day1 ) ,
			(SELECT sum(fee) as Wednesday_l from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '3' and status='confirm'   union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '3' and status='confirm' )x group by day1 )    ,
			(SELECT sum(fee) as Thursday_l from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '4' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '4' and status='confirm' )x group by day1 )    ,
			(SELECT sum(fee) as Friday_l from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '5' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '5' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Satuday_l from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '6' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '6' and status='confirm' )x group by day1 )  ,
			(SELECT sum(fee) as Sunday_l from ( SELECT day1,time1,fee from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '7' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '7' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Monday from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '1' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '1' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Tuesday from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '2' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '2' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as Wednesday from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '3' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '3' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Thursday from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '4' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '4' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Friday from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '5' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '5' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Satuday from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '6' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '6' and status='confirm' )x group by day1 )  ,
			(SELECT sum(tax) as Sunday from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '7' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' and day1 = '7' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Monday_l from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '1' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '1' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Tuesday_l from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '2' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '2' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Wednesday_l from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '3' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '3' and status='confirm' )x group by day1 ) ,
			(SELECT sum(tax) as Thursday_l from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '4' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '4' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Friday_l from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '5' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '5' and status='confirm' )x group by day1 )  ,
			(SELECT sum(tax) as Satuday_l from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '6' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '6' and status='confirm' )x group by day1 )  ,
			(SELECT sum(tax) as Sunday_l from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '7' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' and day1 = '7' and status='confirm' )x group by day1 )   ,

			(SELECT sum(amount) as Totaljana from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$date."' and time1 = '01' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$date."' and time1 = '01' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as Totalfeba from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$date."' and time1 >= '02' and  time1 < '04' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$date."' and time1 >= '02' and  time1 < '04' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Totalmarcha from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$date."' and time1 >= '04' and  time1 < '06' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$date."' and time1 >= '04' and  time1 < '06' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Totalaprla from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$date."' and time1 >= '06' and  time1 < '08' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$date."' and time1 >= '06' and  time1 < '08' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Totalmaya from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$date."' and time1 >= '08' and  time1 < '10' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$date."' and time1 >= '08' and  time1 < '10' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as Totaljunea from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$date."' and time1 >= '10' and  time1 < '12' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$date."' and time1 >= '10' and  time1 < '12' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Totaljulya from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$date."' and time1 >= '12' and  time1 < '14' and status='confirm'   union all SELECT day1,time1,amount from pos where   date_c = '".$date."' and time1 >= '12' and  time1 < '14' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as Totalaugusta from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$date."' and time1 >= '14' and  time1 < '16' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$date."' and time1 >= '14' and  time1 < '16' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Totalsepa from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$date."' and time1 >= '16' and  time1 < '18' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$date."' and time1 >= '16' and  time1 < '18' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as Totalocta from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$date."' and time1 >= '18' and  time1 < '20' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$date."' and time1 >= '18' and  time1 < '20' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as Totalnova from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$date."' and time1 >= '20' and  time1 < '22' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$date."' and time1 >= '20' and  time1 < '22' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as Totaldeca from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$date."' and time1 >= '22' and  time1 < '24' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$date."' and time1 >= '22' and  time1 <= '24' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as Totaljantaxa from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$date."'  and  time1 = '1' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$date."' and  time1 = '1' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as Totalfebtaxa from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$date."'  and time1 >= '02' and  time1 < '04' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$date."'  and time1 >= '02' and  time1 < '04' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Totalmarchtaxa from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$date."'  and time1 >= '04' and  time1 < '06' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$date."'  and time1 >= '04' and  time1 < '06' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as Totalaprltaxa from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$date."'  and time1 >= '06' and  time1 < '08' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$date."'  and time1 >= '06' and  time1 < '08' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Totalmaytaxa from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$date."'  and time1 >= '08' and  time1 < '10' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$date."'  and time1 >= '08' and  time1 < '10' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as Totaljunetaxa from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$date."'  and time1 >= '10' and  time1 < '12' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$date."'  and time1 >= '10' and  time1 < '12' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Totaljulytaxa from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$date."'  and time1 >= '12' and  time1 < '14' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c = '".$date."'  and time1 >= '12' and  time1 < '14' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Totalaugusttaxa from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$date."'  and time1 >= '14' and  time1 < '16' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$date."'  and time1 >= '14' and  time1 < '16' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Totalseptaxa from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$date."'  and time1 >= '16' and  time1 < '18' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$date."'  and time1 >= '16' and  time1 < '18' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as Totalocttaxa from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$date."'  and time1 >= '18' and  time1 < '20' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$date."'  and time1 >= '18' and  time1 < '20' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as Totalnovtaxa from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$date."'  and time1 >= '20' and  time1 < '22' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$date."'  and time1 >= '20' and  time1 < '22' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as Totaldectaxa from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$date."'  and time1 >= '22' and  time1 < '24' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c = '".$date."'  and time1 >= '22' and  time1 <= '24' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Totaljanfeea from ( SELECT day1,time1,fee from customer_payment_request where   date_c = '".$date."'  and  time1 = '01' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c = '".$date."'   and  time1 = '01' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Totalfebfeea from ( SELECT day1,time1,fee from customer_payment_request where   date_c = '".$date."'  and time1 >= '02' and  time1 < '04' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c = '".$date."'  and time1 >= '02' and  time1 < '04' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Totalmarchfeea from ( SELECT day1,time1,fee from customer_payment_request where   date_c = '".$date."'  and time1 >= '04' and  time1 < '06' and status='confirm'  union all SELECT day1,time1,fee from pos where   date_c = '".$date."'  and time1 >= '04' and  time1 < '06' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Totalaprlfeea from ( SELECT day1,time1,fee from customer_payment_request where   date_c = '".$date."'  and time1 >= '06' and  time1 < '08' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c = '".$date."'  and time1 >= '06' and  time1 < '08' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Totalmayfeea from ( SELECT day1,time1,fee from customer_payment_request where   date_c = '".$date."'  and time1 >= '08' and  time1 < '10' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c = '".$date."'  and time1 >= '08' and  time1 < '10' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Totaljunefeea from ( SELECT day1,time1,fee from customer_payment_request where   date_c = '".$date."'  and time1 >= '10' and  time1 < '12' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c = '".$date."'  and time1 >= '10' and  time1 < '12' and status='confirm' )x group by day1 )    ,
			(SELECT sum(fee) as Totaljulyfeea from ( SELECT day1,time1,fee from customer_payment_request where   date_c = '".$date."'  and time1 >= '12' and  time1 < '14' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c = '".$date."'  and time1 >= '12' and  time1 < '14' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Totalaugustfeea from ( SELECT day1,time1,fee from customer_payment_request where   date_c = '".$date."'  and time1 >= '14' and  time1 < '16' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c = '".$date."'  and time1 >= '14' and  time1 < '16' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Totalsepfeea from ( SELECT day1,time1,fee from customer_payment_request where   date_c = '".$date."'  and time1 >= '16' and  time1 < '18' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c = '".$date."'  and time1 >= '16' and  time1 < '18' and status='confirm' )x group by day1 )    ,
			(SELECT sum(fee) as Totaloctfee from ( SELECT day1,time1,fee from customer_payment_request where   date_c = '".$date."'  and time1 >= '18' and  time1 < '20' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c = '".$date."'  and time1 >= '18' and  time1 < '20' and status='confirm' )x group by day1 )   ,
			(SELECT sum(fee) as Totalnovfeea from ( SELECT day1,time1,fee from customer_payment_request where   date_c = '".$date."'  and time1 >= '20' and  time1 < '22' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c = '".$date."'  and time1 >= '20' and  time1 < '22' and status='confirm' )x group by day1 )  ,
			(SELECT sum(fee) as Totaldecfeea from ( SELECT day1,time1,fee from customer_payment_request where   date_c = '".$date."'  and time1 >= '22' and  time1 < '24' and status='confirm'    union all SELECT day1,time1,fee from pos where   date_c = '".$date."'  and time1 >= '22' and  time1 < '24' and status='confirm' )x group by day1 ) ,

			(SELECT sum(amount) as Totaljan from ( SELECT month,amount from customer_payment_request where   month = '01' and year = '".$today2."' and status='confirm'    union all SELECT month,amount from pos where   month = '01' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(amount) as Totalfeb from ( SELECT month,amount from customer_payment_request where   month = '02' and year = '".$today2."' and status='confirm'    union all SELECT month,amount from pos where   month = '02' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(amount) as Totalmarch from ( SELECT month,amount from customer_payment_request where   month = '03' and year = '".$today2."' and status='confirm'    union all SELECT month,amount from pos where   month = '03' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(amount) as Totalaprl from ( SELECT month,amount from customer_payment_request where   month = '04' and year = '".$today2."' and status='confirm'   union all SELECT month,amount from pos where   month = '04' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(amount) as Totalmay from ( SELECT month,amount from customer_payment_request where   month = '05' and year = '".$today2."' and status='confirm'    union all SELECT month,amount from pos where   month = '05' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(amount) as Totaljune from ( SELECT month,amount from customer_payment_request where   month = '06' and year = '".$today2."' and status='confirm'   union all SELECT month,amount from pos where   month = '06' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(amount) as Totaljuly from ( SELECT month,amount from customer_payment_request where   month = '07' and year = '".$today2."' and status='confirm'    union all SELECT month,amount from pos where   month = '07' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(amount) as Totalaugust from ( SELECT month,amount from customer_payment_request where   month = '08' and year = '".$today2."' and status='confirm'  union all SELECT month,amount from pos where   month = '08' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(amount) as Totalsep from ( SELECT month,amount from customer_payment_request where   month = '09' and year = '".$today2."' and status='confirm'   union all SELECT month,amount from pos where   month = '09' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(amount) as Totaloct from ( SELECT month,amount from customer_payment_request where   month = '10' and year = '".$today2."' and status='confirm'    union all SELECT month,amount from pos where   month = '10' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(amount) as Totalnov from ( SELECT month,amount from customer_payment_request where   month = '11' and year = '".$today2."' and status='confirm'   union all SELECT month,amount from pos where   month = '11' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(amount) as Totaldec from ( SELECT month,amount from customer_payment_request where   month = '12' and year = '".$today2."' and status='confirm' union all SELECT month,amount from pos where   month = '12' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totaljanf from ( SELECT month,fee from customer_payment_request where   month = '01' and year = '".$today2."' and status='confirm'   union all SELECT month,fee from pos where   month = '01' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalfebf from ( SELECT month,fee from customer_payment_request where   month = '02' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '02' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalmarchf from ( SELECT month,fee from customer_payment_request where   month = '03' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '03' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalaprlf from ( SELECT month,fee from customer_payment_request where   month = '04' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '04' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalmayf from ( SELECT month,fee from customer_payment_request where   month = '05' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '05' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(fee) as Totaljunef from ( SELECT month,fee from customer_payment_request where   month = '06' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '06' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totaljulyf from ( SELECT month,fee from customer_payment_request where   month = '07' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '07' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(fee) as Totalaugustf from ( SELECT month,fee from customer_payment_request where   month = '08' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '08' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalsepf from ( SELECT month,fee from customer_payment_request where   month = '09' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '09' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totaloctf from ( SELECT month,fee from customer_payment_request where   month = '10' and year = '".$today2."' and status='confirm' union all SELECT month,fee from pos where   month = '10' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalnovf from ( SELECT month,fee from customer_payment_request where   month = '11' and year = '".$today2."' and status='confirm'   union all SELECT month,fee from pos where   month = '11' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totaldecf from ( SELECT month,fee from customer_payment_request where   month = '12' and year = '".$today2."' and status='confirm'   union all SELECT month,fee from pos where   month = '12' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(tax) as Totaljantax from ( SELECT month,tax from customer_payment_request where   month = '01' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '01' and year = '".$today2."' and status='confirm' )x group by month )    ,
			(SELECT sum(tax) as Totalfebtax from ( SELECT month,tax from customer_payment_request where   month = '02' and year = '".$today2."' and status='confirm'   union all SELECT month,tax from pos where   month = '02' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalmarchtax from ( SELECT month,tax from customer_payment_request where   month = '03' and year = '".$today2."' and status='confirm'   union all SELECT month,tax from pos where   month = '03' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalaprltax from ( SELECT month,tax from customer_payment_request where   month = '04' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '04' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalmaytax from ( SELECT month,tax from customer_payment_request where   month = '05' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '05' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totaljunetax from ( SELECT month,tax from customer_payment_request where   month = '06' and year = '".$today2."' and status='confirm'   union all SELECT month,tax from pos where   month = '06' and year = '".$today2."' and status='confirm' )x group by month )    ,
			(SELECT sum(tax) as Totaljulytax from ( SELECT month,tax from customer_payment_request where   month = '07' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '07' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(tax) as Totalaugusttax from ( SELECT month,tax from customer_payment_request where   month = '08' and year = '".$today2."' and status='confirm'   union all SELECT month,tax from pos where   month = '08' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(tax) as Totalseptax from ( SELECT month,tax from customer_payment_request where   month = '09' and year = '".$today2."' and status='confirm'   union all SELECT month,tax from pos where   month = '09' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(tax) as Totalocttax from ( SELECT month,tax from customer_payment_request where   month = '10' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '10' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalnovtax from ( SELECT month,tax from customer_payment_request where   month = '11' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '11' and year = '".$today2."' and status='confirm' )x group by month )    ,
			(SELECT sum(tax) as Totaldectax from ( SELECT month,tax from customer_payment_request where   month = '12' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '12' and year = '".$today2."' and status='confirm' )x group by month )    ,
			(SELECT sum(amount) as Totalbjan from ( SELECT month,amount from customer_payment_request where   month = '01' and year = '".$last_year."' and status='confirm'   union all SELECT month,amount from pos where   month = '01' and year = '".$last_year."' and status='confirm' ) x group by month )   ,
			(SELECT sum(amount) as Totalbfeb from ( SELECT month,amount from customer_payment_request where   month = '02' and year = '".$last_year."' and status='confirm'   union all SELECT month,amount from pos where   month = '02' and year = '".$last_year."' and status='confirm' ) x group by month )  ,
			(SELECT sum(amount) as Totalbmarch from ( SELECT month,amount from customer_payment_request where   month = '03' and year = '".$last_year."' and status='confirm'   union all SELECT month,amount from pos where   month = '03' and year = '".$last_year."' and status='confirm' ) x group by month )   ,
			(SELECT sum(amount) as Totalbaprl from ( SELECT month,amount from customer_payment_request where   month = '04' and year = '".$last_year."' and status='confirm'   union all SELECT month,amount from pos where   month = '04' and year = '".$last_year."' and status='confirm' ) x group by month )  ,
			(SELECT sum(amount) as Totalbmay from ( SELECT month,amount from customer_payment_request where   month = '05' and year = '".$last_year."' and status='confirm'    union all SELECT month,amount from pos where   month = '05' and year = '".$last_year."' and status='confirm' ) x group by month )   ,
			(SELECT sum(amount) as Totalbjune from ( SELECT month,amount from customer_payment_request where   month = '06' and year = '".$last_year."' and status='confirm'    union all SELECT month,amount from pos where   month = '06' and year = '".$last_year."' and status='confirm' ) x group by month )   ,
			(SELECT sum(amount) as Totalbjuly from ( SELECT month,amount from customer_payment_request where   month = '07' and year = '".$last_year."' and status='confirm'    union all SELECT month,amount from pos where   month = '07' and year = '".$last_year."' and status='confirm' ) x group by month )    ,
			(SELECT sum(amount) as Totalbaugust from ( SELECT month,amount from customer_payment_request where   month = '08' and year = '".$last_year."' and status='confirm'   union all SELECT month,amount from pos where   month = '08' and year = '".$last_year."' and status='confirm' ) x group by month )    ,
			(SELECT sum(amount) as Totalbsep from ( SELECT month,amount from customer_payment_request where   month = '09' and year = '".$last_year."' and status='confirm'    union all SELECT month,amount from pos where   month = '09' and year = '".$last_year."' and status='confirm' ) x group by month )   ,
			(SELECT sum(amount) as Totalboct from ( SELECT month,amount from customer_payment_request where   month = '10' and year = '".$last_year."' and status='confirm'   union all SELECT month,amount from pos where   month = '10' and year = '".$last_year."' and status='confirm' ) x group by month )    ,
			(SELECT sum(amount) as Totalbnov from ( SELECT month,amount from customer_payment_request where   month = '11' and year = '".$last_year."' and status='confirm'    union all SELECT month,amount from pos where   month = '11' and year = '".$last_year."' and status='confirm' ) x group by month )   ,
			(SELECT sum(amount) as Totalbdec from ( SELECT month,amount from customer_payment_request where   month = '12' and year = '".$last_year."' and status='confirm'    union all SELECT month,amount from pos where   month = '12' and year = '".$last_year."' and status='confirm' ) x group by month ) ,
			(SELECT sum(fee) as Totalbjanf from ( SELECT month,fee from customer_payment_request where   month = '01' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '01' and year = '".$last_year."' and status='confirm' )x group by month )  ,
			(SELECT sum(fee) as Totalbfebf from ( SELECT month,fee from customer_payment_request where   month = '02' and year = '".$last_year."' and status='confirm'   union all SELECT month,fee from pos where   month = '02' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalbmarchf from ( SELECT month,fee from customer_payment_request where   month = '03' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '03' and year = '".$last_year."' and status='confirm' )x group by month )  ,
			(SELECT sum(fee) as Totalbaprlf from ( SELECT month,fee from customer_payment_request where   month = '04' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '04' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalbmayf from ( SELECT month,fee from customer_payment_request where   month = '05' and year = '".$last_year."' and status='confirm'   union all SELECT month,fee from pos where   month = '05' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalbjunef from ( SELECT month,fee from customer_payment_request where   month = '06' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '06' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalbjulyf from ( SELECT month,fee from customer_payment_request where   month = '07' and year = '".$last_year."' and status='confirm'   union all SELECT month,fee from pos where   month = '07' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalbaugustf from ( SELECT month,fee from customer_payment_request where   month = '08' and year = '".$last_year."' and status='confirm'   union all SELECT month,fee from pos where   month = '08' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalbsepf from ( SELECT month,fee from customer_payment_request where   month = '09' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '09' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalboctf from ( SELECT month,fee from customer_payment_request where   month = '10' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '10' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalbnovf from ( SELECT month,fee from customer_payment_request where   month = '11' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '11' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalbdecf from ( SELECT month,fee from customer_payment_request where   month = '12' and year = '".$last_year."' and status='confirm'   union all SELECT month,fee from pos where   month = '12' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbjantax from ( SELECT month,tax from customer_payment_request where   month = '01' and year = '".$last_year."' and status='confirm'   union all SELECT month,tax from pos where   month = '01' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbfebtax from ( SELECT month,tax from customer_payment_request where   month = '02' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '02' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(tax) as Totalbmarchtax from ( SELECT month,tax from customer_payment_request where   month = '03' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '03' and year = '".$last_year."' and status='confirm' )x group by month )  ,
			(SELECT sum(tax) as Totalbaprltax from ( SELECT month,tax from customer_payment_request where   month = '04' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '04' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbmaytax from ( SELECT month,tax from customer_payment_request where   month = '05' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '05' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbjunetax from ( SELECT month,tax from customer_payment_request where   month = '06' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '06' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbjulytax from ( SELECT month,tax from customer_payment_request where   month = '07' and year = '".$last_year."' and status='confirm'   union all SELECT month,tax from pos where   month = '07' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbaugusttax from ( SELECT month,tax from customer_payment_request where   month = '08' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '08' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbseptax from ( SELECT month,tax from customer_payment_request where   month = '09' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '09' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbocttax from ( SELECT month,tax from customer_payment_request where   month = '10' and year = '".$last_year."' and status='confirm'   union all SELECT month,tax from pos where   month = '10' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbnovtax from ( SELECT month,tax from customer_payment_request where   month = '11' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '11' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbdectax from ( SELECT month,tax from customer_payment_request where   month = '12' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '12' and year = '".$last_year."' and status='confirm' )x group by month )   ) 
		");
		//echo $this->db->last_query();die;
		
	}

	public function dashboard_sale_by_year() {
		$today2 = date("Y");
		$last_year = date("Y",strtotime("-1 year"));
		
		$getDashboard = $this->db->query("INSERT INTO admin_year_graph values ('', 
			(SELECT sum(amount) as Totaljan from ( SELECT month,amount from customer_payment_request where   month = '01' and year = '".$today2."' and status='confirm'    union all SELECT month,amount from pos where   month = '01' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(amount) as Totalfeb from ( SELECT month,amount from customer_payment_request where   month = '02' and year = '".$today2."' and status='confirm'    union all SELECT month,amount from pos where   month = '02' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(amount) as Totalmarch from ( SELECT month,amount from customer_payment_request where   month = '03' and year = '".$today2."' and status='confirm'    union all SELECT month,amount from pos where   month = '03' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(amount) as Totalaprl from ( SELECT month,amount from customer_payment_request where   month = '04' and year = '".$today2."' and status='confirm'   union all SELECT month,amount from pos where   month = '04' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(amount) as Totalmay from ( SELECT month,amount from customer_payment_request where   month = '05' and year = '".$today2."' and status='confirm'    union all SELECT month,amount from pos where   month = '05' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(amount) as Totaljune from ( SELECT month,amount from customer_payment_request where   month = '06' and year = '".$today2."' and status='confirm'   union all SELECT month,amount from pos where   month = '06' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(amount) as Totaljuly from ( SELECT month,amount from customer_payment_request where   month = '07' and year = '".$today2."' and status='confirm'    union all SELECT month,amount from pos where   month = '07' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(amount) as Totalaugust from ( SELECT month,amount from customer_payment_request where   month = '08' and year = '".$today2."' and status='confirm'  union all SELECT month,amount from pos where   month = '08' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(amount) as Totalsep from ( SELECT month,amount from customer_payment_request where   month = '09' and year = '".$today2."' and status='confirm'   union all SELECT month,amount from pos where   month = '09' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(amount) as Totaloct from ( SELECT month,amount from customer_payment_request where   month = '10' and year = '".$today2."' and status='confirm'    union all SELECT month,amount from pos where   month = '10' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(amount) as Totalnov from ( SELECT month,amount from customer_payment_request where   month = '11' and year = '".$today2."' and status='confirm'   union all SELECT month,amount from pos where   month = '11' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(amount) as Totaldec from ( SELECT month,amount from customer_payment_request where   month = '12' and year = '".$today2."' and status='confirm' union all SELECT month,amount from pos where   month = '12' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(fee) as Totaljanf from ( SELECT month,fee from customer_payment_request where   month = '01' and year = '".$today2."' and status='confirm'   union all SELECT month,fee from pos where   month = '01' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(fee) as Totalfebf from ( SELECT month,fee from customer_payment_request where   month = '02' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '02' and year = '".$today2."' and status='confirm' )x group by month ),
			(SELECT sum(fee) as Totalmarchf from ( SELECT month,fee from customer_payment_request where   month = '03' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '03' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(fee) as Totalaprlf from ( SELECT month,fee from customer_payment_request where   month = '04' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '04' and year = '".$today2."' and status='confirm' )x group by month ),
			(SELECT sum(fee) as Totalmayf from ( SELECT month,fee from customer_payment_request where   month = '05' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '05' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(fee) as Totaljunef from ( SELECT month,fee from customer_payment_request where   month = '06' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '06' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(fee) as Totaljulyf from ( SELECT month,fee from customer_payment_request where   month = '07' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '07' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(fee) as Totalaugustf from ( SELECT month,fee from customer_payment_request where   month = '08' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '08' and year = '".$today2."' and status='confirm' )x group by month ),
			(SELECT sum(fee) as Totalsepf from ( SELECT month,fee from customer_payment_request where   month = '09' and year = '".$today2."' and status='confirm'    union all SELECT month,fee from pos where   month = '09' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(fee) as Totaloctf from ( SELECT month,fee from customer_payment_request where   month = '10' and year = '".$today2."' and status='confirm' union all SELECT month,fee from pos where   month = '10' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(fee) as Totalnovf from ( SELECT month,fee from customer_payment_request where   month = '11' and year = '".$today2."' and status='confirm'   union all SELECT month,fee from pos where   month = '11' and year = '".$today2."' and status='confirm' )x group by month ),
			(SELECT sum(fee) as Totaldecf from ( SELECT month,fee from customer_payment_request where   month = '12' and year = '".$today2."' and status='confirm'   union all SELECT month,fee from pos where   month = '12' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(tax) as Totaljantax from ( SELECT month,tax from customer_payment_request where   month = '01' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '01' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(tax) as Totalfebtax from ( SELECT month,tax from customer_payment_request where   month = '02' and year = '".$today2."' and status='confirm'   union all SELECT month,tax from pos where   month = '02' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(tax) as Totalmarchtax from ( SELECT month,tax from customer_payment_request where   month = '03' and year = '".$today2."' and status='confirm'   union all SELECT month,tax from pos where   month = '03' and year = '".$today2."' and status='confirm' )x group by month ),
			(SELECT sum(tax) as Totalaprltax from ( SELECT month,tax from customer_payment_request where   month = '04' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '04' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(tax) as Totalmaytax from ( SELECT month,tax from customer_payment_request where   month = '05' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '05' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(tax) as Totaljunetax from ( SELECT month,tax from customer_payment_request where   month = '06' and year = '".$today2."' and status='confirm'   union all SELECT month,tax from pos where   month = '06' and year = '".$today2."' and status='confirm' )x group by month )  ,
			(SELECT sum(tax) as Totaljulytax from ( SELECT month,tax from customer_payment_request where   month = '07' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '07' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalaugusttax from ( SELECT month,tax from customer_payment_request where   month = '08' and year = '".$today2."' and status='confirm'   union all SELECT month,tax from pos where   month = '08' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(tax) as Totalseptax from ( SELECT month,tax from customer_payment_request where   month = '09' and year = '".$today2."' and status='confirm'   union all SELECT month,tax from pos where   month = '09' and year = '".$today2."' and status='confirm' )x group by month ) ,
			(SELECT sum(tax) as Totalocttax from ( SELECT month,tax from customer_payment_request where   month = '10' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '10' and year = '".$today2."' and status='confirm' )x group by month ),
			(SELECT sum(tax) as Totalnovtax from ( SELECT month,tax from customer_payment_request where   month = '11' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '11' and year = '".$today2."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totaldectax from ( SELECT month,tax from customer_payment_request where   month = '12' and year = '".$today2."' and status='confirm'    union all SELECT month,tax from pos where   month = '12' and year = '".$today2."' and status='confirm' )x group by month ),
			(SELECT sum(amount) as Totalbjan from ( SELECT month,amount from customer_payment_request where   month = '01' and year = '".$last_year."' and status='confirm'   union all SELECT month,amount from pos where   month = '01' and year = '".$last_year."' and status='confirm' ) x group by month ) ,
			(SELECT sum(amount) as Totalbfeb from ( SELECT month,amount from customer_payment_request where   month = '02' and year = '".$last_year."' and status='confirm'   union all SELECT month,amount from pos where   month = '02' and year = '".$last_year."' and status='confirm' ) x group by month ) ,
			(SELECT sum(amount) as Totalbmarch from ( SELECT month,amount from customer_payment_request where   month = '03' and year = '".$last_year."' and status='confirm'   union all SELECT month,amount from pos where   month = '03' and year = '".$last_year."' and status='confirm' ) x group by month )  ,
			(SELECT sum(amount) as Totalbaprl from ( SELECT month,amount from customer_payment_request where   month = '04' and year = '".$last_year."' and status='confirm'   union all SELECT month,amount from pos where   month = '04' and year = '".$last_year."' and status='confirm' ) x group by month )   ,
			(SELECT sum(amount) as Totalbmay from ( SELECT month,amount from customer_payment_request where   month = '05' and year = '".$last_year."' and status='confirm'    union all SELECT month,amount from pos where   month = '05' and year = '".$last_year."' and status='confirm' ) x group by month )    ,
			(SELECT sum(amount) as Totalbjune from ( SELECT month,amount from customer_payment_request where   month = '06' and year = '".$last_year."' and status='confirm'    union all SELECT month,amount from pos where   month = '06' and year = '".$last_year."' and status='confirm' ) x group by month )   ,
			(SELECT sum(amount) as Totalbjuly from ( SELECT month,amount from customer_payment_request where   month = '07' and year = '".$last_year."' and status='confirm'    union all SELECT month,amount from pos where   month = '07' and year = '".$last_year."' and status='confirm' ) x group by month )  ,
			(SELECT sum(amount) as Totalbaugust from ( SELECT month,amount from customer_payment_request where   month = '08' and year = '".$last_year."' and status='confirm'   union all SELECT month,amount from pos where   month = '08' and year = '".$last_year."' and status='confirm' ) x group by month )   ,
			(SELECT sum(amount) as Totalbsep from ( SELECT month,amount from customer_payment_request where   month = '09' and year = '".$last_year."' and status='confirm'    union all SELECT month,amount from pos where   month = '09' and year = '".$last_year."' and status='confirm' ) x group by month )   ,
			(SELECT sum(amount) as Totalboct from ( SELECT month,amount from customer_payment_request where   month = '10' and year = '".$last_year."' and status='confirm'   union all SELECT month,amount from pos where   month = '10' and year = '".$last_year."' and status='confirm' ) x group by month )   ,
			(SELECT sum(amount) as Totalbnov from ( SELECT month,amount from customer_payment_request where   month = '11' and year = '".$last_year."' and status='confirm'    union all SELECT month,amount from pos where   month = '11' and year = '".$last_year."' and status='confirm' ) x group by month )    ,
			(SELECT sum(amount) as Totalbdec from ( SELECT month,amount from customer_payment_request where   month = '12' and year = '".$last_year."' and status='confirm'    union all SELECT month,amount from pos where   month = '12' and year = '".$last_year."' and status='confirm' ) x group by month )  ,
			(SELECT sum(fee) as Totalbjanf from ( SELECT month,fee from customer_payment_request where   month = '01' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '01' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(fee) as Totalbfebf from ( SELECT month,fee from customer_payment_request where   month = '02' and year = '".$last_year."' and status='confirm'   union all SELECT month,fee from pos where   month = '02' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(fee) as Totalbmarchf from ( SELECT month,fee from customer_payment_request where   month = '03' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '03' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(fee) as Totalbaprlf from ( SELECT month,fee from customer_payment_request where   month = '04' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '04' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalbmayf from ( SELECT month,fee from customer_payment_request where   month = '05' and year = '".$last_year."' and status='confirm'   union all SELECT month,fee from pos where   month = '05' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(fee) as Totalbjunef from ( SELECT month,fee from customer_payment_request where   month = '06' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '06' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalbjulyf from ( SELECT month,fee from customer_payment_request where   month = '07' and year = '".$last_year."' and status='confirm'   union all SELECT month,fee from pos where   month = '07' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalbaugustf from ( SELECT month,fee from customer_payment_request where   month = '08' and year = '".$last_year."' and status='confirm'   union all SELECT month,fee from pos where   month = '08' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(fee) as Totalbsepf from ( SELECT month,fee from customer_payment_request where   month = '09' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '09' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(fee) as Totalboctf from ( SELECT month,fee from customer_payment_request where   month = '10' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '10' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(fee) as Totalbnovf from ( SELECT month,fee from customer_payment_request where   month = '11' and year = '".$last_year."' and status='confirm'    union all SELECT month,fee from pos where   month = '11' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(fee) as Totalbdecf from ( SELECT month,fee from customer_payment_request where   month = '12' and year = '".$last_year."' and status='confirm'   union all SELECT month,fee from pos where   month = '12' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(tax) as Totalbjantax from ( SELECT month,tax from customer_payment_request where   month = '01' and year = '".$last_year."' and status='confirm'   union all SELECT month,tax from pos where   month = '01' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(tax) as Totalbfebtax from ( SELECT month,tax from customer_payment_request where   month = '02' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '02' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(tax) as Totalbmarchtax from ( SELECT month,tax from customer_payment_request where   month = '03' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '03' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(tax) as Totalbaprltax from ( SELECT month,tax from customer_payment_request where   month = '04' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '04' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(tax) as Totalbmaytax from ( SELECT month,tax from customer_payment_request where   month = '05' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '05' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbjunetax from ( SELECT month,tax from customer_payment_request where   month = '06' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '06' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbjulytax from ( SELECT month,tax from customer_payment_request where   month = '07' and year = '".$last_year."' and status='confirm'   union all SELECT month,tax from pos where   month = '07' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbaugusttax from ( SELECT month,tax from customer_payment_request where   month = '08' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '08' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(tax) as Totalbseptax from ( SELECT month,tax from customer_payment_request where   month = '09' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '09' and year = '".$last_year."' and status='confirm' )x group by month )  ,
			(SELECT sum(tax) as Totalbocttax from ( SELECT month,tax from customer_payment_request where   month = '10' and year = '".$last_year."' and status='confirm'   union all SELECT month,tax from pos where   month = '10' and year = '".$last_year."' and status='confirm' )x group by month )   ,
			(SELECT sum(tax) as Totalbnovtax from ( SELECT month,tax from customer_payment_request where   month = '11' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '11' and year = '".$last_year."' and status='confirm' )x group by month )    ,
			(SELECT sum(tax) as Totalbdectax from ( SELECT month,tax from customer_payment_request where   month = '12' and year = '".$last_year."' and status='confirm'    union all SELECT month,tax from pos where   month = '12' and year = '".$last_year."' and status='confirm' )x group by month )  ) 
		");

		// echo $this->db->last_query();die;
		
	}
}
?>