<?php
ini_set('MAX_EXECUTION_TIME', '-1');
ini_set('memory_limit','2048M');
if ( ! defined('BASEPATH')) exit('No direct script access allowed');
 
class Admin_Chart extends CI_Controller {
 	public function __construct() {
 	    
		parent::__construct();
		$this->load->helper('form');
		$this->load->helper('url');
		$this->load->helper('html');
		$this->load->model('profile_model');
		$this->load->model('admin_model');
		$this->load->model('home_model');
		$this->load->library('form_validation');
		$this->load->library('email');
		date_default_timezone_set("America/Chicago");
		ini_set('display_errors', 1);
	    error_reporting(E_ALL);
	}

	public function trends_original() {
		//daily
		$current_date = date("Y-m-d");
		$last_date = date("Y-m-d",strtotime("-1 days"));
		// echo $current_date.','.$last_date;die;

		//weeekly
		// $cday = date("Y-m-d",strtotime("-1 days"));
		// $lday = date("Y-m-d",strtotime("-8 days")); 
		$monday = strtotime("last monday");
		$monday = date('w', $monday)==date('w') ? $monday+7*86400 : $monday;
		$sunday = strtotime(date("Y-m-d",$monday)." +6 days");
		$sunday1 = strtotime(date("Y-m-d",$monday)." -7 days");
		$sunday2 = strtotime(date("Y-m-d",$sunday1)." +6 days");
		//current week
		$this_week_sd = date("Y-m-d",$monday);
		$this_week_ed = date("Y-m-d",$sunday);
		//last week
		$this_week_ed1 = date("Y-m-d",$sunday2);
		$this_week_sd1 = date("Y-m-d",$sunday1);

		//yearly
		$this_year = date("Y");
		$last_year = date("Y",strtotime("-1 year"));
		$query=$this->db->query("SELECT wf_merchants from admin where id='9'")->result_array();
        $wf_merchants=$query[0]['wf_merchants']; 
		$stmt=" and merchant_id IN('";
		if(!empty($wf_merchants)) {
	        $x=explode(",",$wf_merchants);
	        $len=sizeof($x);
	        for ($i=0; $i <$len ; $i++) { 
	            if($i==0){
	                $stmt.=$x[$i];
	            }else{
	                $stmt.="','".$x[$i];
	            }
	        
	        }
	        $stmt.="')";

		}else{
			$stmt=' and merchant_id is null ';

		}
		//echo $stmt;

		$getDashboard = $this->db->query("INSERT INTO sales_trend_admin_wf values ('', 
			(SELECT sum(amount) as CurrAmtDailyOne from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt." and time1 = '01' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt." and time1 = '01' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as CurrAmtDailyTwo from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt." and time1 >= '02' and  time1 < '04' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt." and time1 >= '02' and  time1 < '04' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as CurrAmtDailyThree from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt." and time1 >= '04' and  time1 < '06' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt." and time1 >= '04' and  time1 < '06' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as CurrAmtDailyFour from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt." and time1 >= '06' and  time1 < '08' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt." and time1 >= '06' and  time1 < '08' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as CurrAmtDailyFive from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt." and time1 >= '08' and  time1 < '10' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt." and time1 >= '08' and  time1 < '10' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as CurrAmtDailySix from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt." and time1 >= '10' and  time1 < '12' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt." and time1 >= '10' and  time1 < '12' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as CurrAmtDailySeven from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt." and time1 >= '12' and  time1 < '14' and status='confirm'   union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt." and time1 >= '12' and  time1 < '14' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as CurrAmtDailyEight from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt." and time1 >= '14' and  time1 < '16' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt." and time1 >= '14' and  time1 < '16' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as CurrAmtDailyNine from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt." and time1 >= '16' and  time1 < '18' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt." and time1 >= '16' and  time1 < '18' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as CurrAmtDailyTen from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt." and time1 >= '18' and  time1 < '20' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt." and time1 >= '18' and  time1 < '20' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as CurrAmtDailyEleven from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt." and time1 >= '20' and  time1 < '22' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt." and time1 >= '20' and  time1 < '22' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as CurrAmtDailyTwelve from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt." and time1 >= '22' and  time1 < '24' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt." and time1 >= '22' and  time1 <= '24' and status='confirm' )x group by day1 )    ,

			(SELECT avg(amount) as CurrAvgDailyOne from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt."  and  time1 = '01' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt."   and  time1 = '01' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as CurrAvgDailyTwo from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt."  and time1 >= '02' and  time1 < '04' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt."  and time1 >= '02' and  time1 < '04' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as CurrAvgDailyThree from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt."  and time1 >= '04' and  time1 < '06' and status='confirm'  union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt."  and time1 >= '04' and  time1 < '06' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as CurrAvgDailyFour from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt."  and time1 >= '06' and  time1 < '08' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt."  and time1 >= '06' and  time1 < '08' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as CurrAvgDailyFive from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt."  and time1 >= '08' and  time1 < '10' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt."  and time1 >= '08' and  time1 < '10' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as CurrAvgDailySix from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt."  and time1 >= '10' and  time1 < '12' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt."  and time1 >= '10' and  time1 < '12' and status='confirm' )x group by day1 )    ,
			(SELECT avg(amount) as CurrAvgDailySeven from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt."  and time1 >= '12' and  time1 < '14' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt."  and time1 >= '12' and  time1 < '14' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as CurrAvgDailyEight from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt."  and time1 >= '14' and  time1 < '16' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt."  and time1 >= '14' and  time1 < '16' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as CurrAvgDailyNine from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt."  and time1 >= '16' and  time1 < '18' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt."  and time1 >= '16' and  time1 < '18' and status='confirm' )x group by day1 )    ,
			(SELECT avg(amount) as CurrAvgDailyTen from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt."  and time1 >= '18' and  time1 < '20' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt."  and time1 >= '18' and  time1 < '20' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as CurrAvgDailyEleven from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt."  and time1 >= '20' and  time1 < '22' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt."  and time1 >= '20' and  time1 < '22' and status='confirm' )x group by day1 )  ,
			(SELECT avg(amount) as CurrAvgDailyTwelve from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$current_date."'".$stmt."  and time1 >= '22' and  time1 < '24' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$current_date."'".$stmt."  and time1 >= '22' and  time1 < '24' and status='confirm' )x group by day1 ) ,

			(SELECT sum(tax) as CurrTaxDailyOne from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$current_date."' $stmt  and  time1 = '01' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$current_date."' $stmt and  time1 = '01' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as CurrTaxDailyTwo from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$current_date."' $stmt  and time1 >= '02' and  time1 < '04' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$current_date."' $stmt  and time1 >= '02' and  time1 < '04' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as CurrTaxDailyThree from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$current_date."' $stmt and time1 >= '04' and  time1 < '06' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$current_date."' $stmt and time1 >= '04' and  time1 < '06' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as CurrTaxDailyFour from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$current_date."' $stmt  and time1 >= '06' and  time1 < '08' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$current_date."' $stmt and time1 >= '06' and  time1 < '08' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as CurrTaxDailyFive from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$current_date."' $stmt and time1 >= '08' and  time1 < '10' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$current_date."' $stmt  and time1 >= '08' and  time1 < '10' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as CurrTaxDailySix from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$current_date."' $stmt and time1 >= '10' and  time1 < '12' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$current_date."' $stmt and time1 >= '10' and  time1 < '12' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as CurrTaxDailySeven from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$current_date."' $stmt  and time1 >= '12' and  time1 < '14' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c = '".$current_date."' $stmt and time1 >= '12' and  time1 < '14' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as CurrTaxDailyEight from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$current_date."' $stmt  and time1 >= '14' and  time1 < '16' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$current_date."' $stmt and time1 >= '14' and  time1 < '16' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as CurrTaxDailyNine from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$current_date."' $stmt and time1 >= '16' and  time1 < '18' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$current_date."' $stmt  and time1 >= '16' and  time1 < '18' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as CurrTaxDailyTen from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$current_date."' $stmt  and time1 >= '18' and  time1 < '20' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$current_date."' $stmt  and time1 >= '18' and  time1 < '20' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as CurrTaxDailyEleven from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$current_date."' $stmt  and time1 >= '20' and  time1 < '22' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$current_date."' $stmt  and time1 >= '20' and  time1 < '22' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as CurrTaxDailyTwelve from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$current_date."' $stmt  and time1 >= '22' and  time1 < '24' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c = '".$current_date."' $stmt and time1 >= '22' and  time1 <= '24' and status='confirm' )x group by day1 )   ,

			(SELECT sum(amount) as LastAmtDailyOne from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 = '01' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 = '01' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as LastAmtDailyTwo from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '02' and  time1 < '04' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '02' and  time1 < '04' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as LastAmtDailyThree from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '04' and  time1 < '06' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '04' and  time1 < '06' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as LastAmtDailyFour from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '06' and  time1 < '08' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '06' and  time1 < '08' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as LastAmtDailyFive from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '08' and  time1 < '10' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '08' and  time1 < '10' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as LastAmtDailySix from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '10' and  time1 < '12' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '10' and  time1 < '12' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as LastAmtDailySeven from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '12' and  time1 < '14' and status='confirm'   union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '12' and  time1 < '14' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as LastAmtDailyEight from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '14' and  time1 < '16' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '14' and  time1 < '16' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as LastAmtDailyNine from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '16' and  time1 < '18' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '16' and  time1 < '18' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as LastAmtDailyTen from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '18' and  time1 < '20' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '18' and  time1 < '20' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as LastAmtDailyEleven from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '20' and  time1 < '22' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '20' and  time1 < '22' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as LastAmtDailyTwelve from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '22' and  time1 < '24' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '22' and  time1 <= '24' and status='confirm' )x group by day1 )    ,

			(SELECT avg(amount) as LastAvgDailyOne from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and  time1 = '01' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt  and  time1 = '01' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as LastAvgDailyTwo from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '02' and  time1 < '04' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '02' and  time1 < '04' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as LastAvgDailyThree from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '04' and  time1 < '06' and status='confirm'  union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '04' and  time1 < '06' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as LastAvgDailyFour from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt  and time1 >= '06' and  time1 < '08' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '06' and  time1 < '08' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as LastAvgDailyFive from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt  and time1 >= '08' and  time1 < '10' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '08' and  time1 < '10' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as LastAvgDailySix from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt  and time1 >= '10' and  time1 < '12' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '10' and  time1 < '12' and status='confirm' )x group by day1 )    ,
			(SELECT avg(amount) as LastAvgDailySeven from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt  and time1 >= '12' and  time1 < '14' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt  and time1 >= '12' and  time1 < '14' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as LastAvgDailyEight from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt  and time1 >= '14' and  time1 < '16' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '14' and  time1 < '16' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as LastAvgDailyNine from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '16' and  time1 < '18' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '16' and  time1 < '18' and status='confirm' )x group by day1 )    ,
			(SELECT avg(amount) as LastAvgDailyTen from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt  and time1 >= '18' and  time1 < '20' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '18' and  time1 < '20' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as LastAvgDailyEleven from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt  and time1 >= '20' and  time1 < '22' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt  and time1 >= '20' and  time1 < '22' and status='confirm' )x group by day1 )  ,
			(SELECT avg(amount) as LastAvgDailyTwelve from ( SELECT day1,time1,amount from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '22' and  time1 < '24' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c = '".$last_date."' $stmt and time1 >= '22' and  time1 < '24' and status='confirm' )x group by day1 ) ,

			(SELECT sum(tax) as LastTaxDailyOne from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$last_date."' $stmt and  time1 = '1' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$last_date."' $stmt and  time1 = '1' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as LastTaxDailyTwo from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '02' and  time1 < '04' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$last_date."' $stmt and time1 >= '02' and  time1 < '04' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as LastTaxDailyThree from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$last_date."' $stmt  and time1 >= '04' and  time1 < '06' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$last_date."' $stmt and time1 >= '04' and  time1 < '06' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as LastTaxDailyFour from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '06' and  time1 < '08' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$last_date."' $stmt and time1 >= '06' and  time1 < '08' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as LastTaxDailyFive from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '08' and  time1 < '10' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$last_date."' $stmt and time1 >= '08' and  time1 < '10' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as LastTaxDailySix from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '10' and  time1 < '12' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$last_date."' $stmt and time1 >= '10' and  time1 < '12' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as LastTaxDailySeven from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '12' and  time1 < '14' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c = '".$last_date."' $stmt and time1 >= '12' and  time1 < '14' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as LastTaxDailyEight from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '14' and  time1 < '16' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$last_date."' $stmt and time1 >= '14' and  time1 < '16' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as LastTaxDailyNine from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '16' and  time1 < '18' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$last_date."' $stmt and time1 >= '16' and  time1 < '18' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as LastTaxDailyTen from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '18' and  time1 < '20' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$last_date."' $stmt and time1 >= '18' and  time1 < '20' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as LastTaxDailyEleven from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '20' and  time1 < '22' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c = '".$last_date."' $stmt and time1 >= '20' and  time1 < '22' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as LastTaxDailyTwelve from ( SELECT day1,time1,tax from customer_payment_request where   date_c = '".$last_date."' $stmt and time1 >= '22' and  time1 < '24' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c = '".$last_date."' $stmt  and time1 >= '22' and  time1 <= '24' and status='confirm' )x group by day1 )   ,

			
			(SELECT sum(amount) as ThisMondayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."'  and date_c >= '".$this_week_sd."' $stmt and day1 = '1' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '1' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as ThisTuesdayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '2' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '2' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as ThisWednesdayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '3' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '3' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as ThisThursdayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '4' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '4' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as ThisFridayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '5' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '5' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as ThisSaturdayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '6' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '6' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as ThisSundayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '7' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '7' and status='confirm' )x group by day1 )    ,

			(SELECT avg(amount) as ThisMondayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."'".$stmt." and date_c >= '".$this_week_sd."' $stmt and day1 = '1' and status='confirm'   union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '1' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as ThisTuesdayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '2' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '2' and status='confirm' )x group by day1 )    ,
			(SELECT avg(amount) as ThisWednesdayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '3' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '3' and status='confirm' )x group by day1 )    ,
			(SELECT avg(amount) as ThisThursdayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '4' and status='confirm'   union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '4' and status='confirm' )x group by day1 )    ,
			(SELECT avg(amount) as ThisFridayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '5' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '5' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as ThisSaturdayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '6' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '6' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as ThisSundayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '7' and status='confirm'   union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '7' and status='confirm' )x group by day1 )    ,

			(SELECT sum(tax) as ThisMondayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '1' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '1' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as ThisTuesdayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '2' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '2' and status='confirm' )x group by day1 )    ,
			(SELECT sum(tax) as ThisWednesdayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '3' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '3' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as ThisThursdayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '4' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '4' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as ThisFridayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '5' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '5' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as ThisSaturdayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '6' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '6' and status='confirm' )x group by day1 )  ,
			(SELECT sum(tax) as ThisSundayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '7' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed."' and date_c >= '".$this_week_sd."' $stmt and day1 = '7' and status='confirm' )x group by day1 )   ,

			(SELECT sum(amount) as LastMondayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '1' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '1' and status='confirm' )x group by day1 )  ,
			(SELECT sum(amount) as LastTuesdayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '2' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '2' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as LastWednesdayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."'  $stmt and day1 = '3' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '3' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as LastThursdayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."'  $stmt and day1 = '4' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '4' and status='confirm' )x group by day1 )   ,
			(SELECT sum(amount) as LastFridayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '5' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '5' and status='confirm' )x group by day1 )  ,
			(SELECT sum(amount) as LastSaturdayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '6' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '6' and status='confirm' )x group by day1 )    ,
			(SELECT sum(amount) as LastSundayAmt from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '7' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '7' and status='confirm' )x group by day1 )   ,
			
			(SELECT avg(amount) as LastMondayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '1' and status='confirm'   union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '1' and status='confirm' )x group by day1 )    ,
			(SELECT avg(amount) as LastTuesdayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '2' and status='confirm'   union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '2' and status='confirm' )x group by day1 ) ,
			(SELECT avg(amount) as LastWednesdayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '3' and status='confirm'   union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '3' and status='confirm' )x group by day1 )    ,
			(SELECT avg(amount) as LastThursdayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '4' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '4' and status='confirm' )x group by day1 )    ,
			(SELECT avg(amount) as LastFridayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '5' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '5' and status='confirm' )x group by day1 )   ,
			(SELECT avg(amount) as LastSaturdayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '6' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '6' and status='confirm' )x group by day1 )  ,
			(SELECT avg(amount) as LastSundayAvg from ( SELECT day1,time1,amount from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '7' and status='confirm'    union all SELECT day1,time1,amount from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '7' and status='confirm' )x group by day1 )   ,
			
			(SELECT sum(tax) as LastMondayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '1' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '1' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as LastTuesdayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '2' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '2' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as LastWednesdayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '3' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '3' and status='confirm' )x group by day1 ) ,
			(SELECT sum(tax) as LastThursdayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '4' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '4' and status='confirm' )x group by day1 )   ,
			(SELECT sum(tax) as LastFridayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '5' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '5' and status='confirm' )x group by day1 )  ,
			(SELECT sum(tax) as LastSaturdayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '6' and status='confirm'   union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '6' and status='confirm' )x group by day1 )  ,
			(SELECT sum(tax) as LastSundayTax from ( SELECT day1,time1,tax from customer_payment_request where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '7' and status='confirm'    union all SELECT day1,time1,tax from pos where   date_c <= '".$this_week_ed1."' and date_c >= '".$this_week_sd1."' $stmt and day1 = '7' and status='confirm' )x group by day1 )  )
		");
		 echo $this->db->last_query();die;
		
	}

	
}
?>